### ISSUE TITLE
Upgrade JDK to 8 and fix NPE in report generation

### ISSUE THREAD

**Issue by azawawi** [ca0abinary/docker-pentaho#2]
First of all thanks for the awesome work done here. First please upgrade the docker file to use OpenJDK 8 since it is the supported version for v7. Please see the [Pentaho v7 Components Reference](https://help.pentaho.com/Documentation/7.0/0D0/160/000#section_10).

Also there is a regression with report generation when headless JDK 7 (not sure jdk 8 has an issue):

You need to add the following:
```
# Fix NPE in non-pdf report generation
# See https://github.com/docker-library/openjdk/issues/73
USER root
RUN apk add --update ttf-dejavu
```

If you would like, I could submit a PR for it.

**Comment by ca0abinary** [comment]
Glad you're enjoying the image! The version of java should be 8 as it's based on `openjdk:8-jre-alpine`. When I ran the container it reported:
```
~$ docker run --rm -it openjdk:8-jre-alpine sh
/ # java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (IcedTea 3.3.0) (Alpine 8.121.13-r0)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

Also I went ahead and added the `ttf-dejavu` package to the base docker image, thanks for discovering that oversight!

An updated build will be available soon on Docker Hub or you can pull from this repository now if you use the Dockerfile here as a base.

**Comment by azawawi** [comment]
Great work. I must have been looking at [wmarinho/docker-pentaho](https://github.com/wmarinho/docker-pentaho). Please let me know when it is finished so I can test it 👍

**Comment by ca0abinary** [comment]
✅ The updated container is available on Docker Hub now.

**Comment by azawawi** [comment]
👍 

Added #3
