### ISSUE TITLE
Upgrade to 7.1 request

### ISSUE THREAD

**Issue by azawawi** [ca0abinary/docker-pentaho#7]
Any plans to upgrade this docker image please to `7.1`?

Source: [7.1 Release notes](http://www.pentaho.com/product/version-7-1-update)

**Comment by ca0abinary** [comment]
Looks like it's not a simple version bump to upgrade. I gave it a shot and there seem to be some new services, so the configs might have changed. My time is limited, if you want to hunt it down I'll be happy to accept a PR. 😄
